[package]
authors = ["knoby <maximilian.brinkmann@gmx.net>"]
edition = "2018"
readme = "README.md"
name = "cortex_app"
version = "0.1.0"

[dependencies]
cortex-m = "*"
cortex-m-rt = "*"
cortex-m-semihosting = "0.3.2"
panic-halt = "0.2.0"
panic-semihosting = "*"
nb = "*"
heapless = "0.4.1"

[dependencies.rc_framing]
path = "../rc_framing"

[dependencies.stm32f1]
version = "0.5.0"
features = ["stm32f103", "rt"]

[dependencies.stm32f1xx-hal]
version = "0.1.1"
features = ["rt", "stm32f103"]

[dependencies.cortex-m-rtfm]
version = "0.4.1"
features = ["timer-queue"]

# this lets you use `cargo fix`!
[[bin]]
name = "cortex_app"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
